### ISSUE TITLE
Can not get access to the paper

### ISSUE THREAD

**Issue by RiskySignal** [THUYimingLi/backdoor-learning-resources#20]
I can't get access to the paper "Trojan Attacks and Defense for Speech Recognition". Did anyone have the same problem?

**Comment by THUYimingLi** [comment]
> I can't get access to the paper "Trojan Attacks and Defense for Speech Recognition". Did anyone have the same problem?

Hi, RiskySignal, thank you for your notification. I recheck the link again and I can't get access to it also. Besides, I also search it on Google, it seems that its original link is invalid.  I am not sure whether this failure is temporary or permanent. It seems that there are no other copies on the Internet besides its original link. If you still want to read it, you may need to contact its authors.

**Comment by RiskySignal** [comment]
Thanks.
